### ISSUE TITLE
Error when compiling a module for luajit or lua51 or lua52

### ISSUE THREAD

**Issue by phil777** [khvzak/mlua#21]
Hello,

I can build the example module for lua53:
```
git clone https://github.com/khvzak/mlua.git
cd mlua/examples/module
sed -i '/^mlua/s/\[.*\]/["luajit", "module"]/' Cargo.toml   ## feature lua53
cargo build
```
But if I do the same for luajit (or lua51 or lua52):
```
sed -i '/^mlua/s/\[.*\]/["luajit", "module"]/' Cargo.toml   ## feature luajit
cargo build
```

I get these errors:
```
error[E0599]: no associated item named `EPSILON` found for type `f64` in the current scope
   --> src/ffi/compat53.rs:292:54
    |
292 |         if (n - i as lua_Number).abs() < lua_Number::EPSILON {
    |                                                      ^^^^^^^ associated item not found in `f64`

error[E0599]: no associated item named `EPSILON` found for type `f64` in the current scope
   --> src/ffi/compat53.rs:318:65
    |
318 |     if ok != 0 && (n - n_int as lua_Number).abs() < lua_Number::EPSILON {
    |                                                                 ^^^^^^^ associated item not found in `f64`
```

This is with rustc 1.41.0.

Is it a bug ?

**Comment by khvzak** [comment]
Thanks for the bug report!

The `EPSILON` value has become available since `1.43.0`
https://doc.rust-lang.org/std/primitive.f64.html#associatedconstant.EPSILON

Probably, the [deprecated way](https://doc.rust-lang.org/std/f64/constant.EPSILON.html) should work with `1.41.0`.
Is there any reasons to use that old version of rustc compiler?

It works with lua >= 5.3 because they have native methods `lua_isinteger` and `lua_tointegerx`.

**Comment by phil777** [comment]
Thanks for your quick answer. I can confirm it works with a recent version of the compiler.

For the record I used the one packaged in ubuntu 19.10, which was not that old in my mind, and when I tested for its EPSILON support, I tried a println!("{:?'}", std::f64::EPSILON), which worked. So this is the deprecated way, and I was wrong.

Thanks again !
